myboot.name=MySpring PROD

# log level : info
logging.level.com.basic.myspringboot=info

# mariadb
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/boot_db
spring.datasource.username=boot
spring.datasource.password=boot
spring.datasource.driverClassName=org.mariadb.jdbc.Driver

# hibernate
spring.jpa.hibernate.ddl-auto=create // 외부 db에서 가져올때 설정해주기
spring.jpa.show-sql=true // 쿼리문 출력
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect // hibernate한테 내가가진 db가 mariadb라고 알려주는 설정
